# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
      
    working_directory: /go/src/github.com/lnxjedi/gopherbot
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `

      # Get the github publishing tool
      - run: go get github.com/lnxjedi/github-release
      # Coverage tool
      - run: go get github.com/mattn/goveralls
      - run: go get -v -t -d ./...

      # Test
      - run:
          name: Run Integration Tests
          command: |
            go test -v --tags 'test integration' -cover -race -coverprofile coverage.out -coverpkg ./... ./bot
            cat bot/test.log

      # Publish coverage
      # - run:
      #     name: Publish Coverage Results
      #     command: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

      # Build
      - run:
          name: Build platform-specific zip archives
          command: ./mkdist.sh

      # Publish
      - deploy:
          name: Publish archives to Github
          command: ./publish.sh
